languages: ["en", "zh"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: zh
languageNames:
  zh: Chinese
  en: English

collections:
  staffs:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "POST"
  - scope:
      path: ""
    values:
      layout: "BASE"